In [1]:
import pandas as pd

df = pd.read_csv("students_placement.csv")

df.head()

   cgpa   iq  profile_score  placed
0  5.97  106             61       0
1  6.83  113             77       0
2  6.60  110             61       0
3  5.54  113             68       0
4  6.84  102             67       0

In [2]:
df.shape

(300, 4)

In [3]:
df.columns

Index(['cgpa', 'iq', 'profile_score', 'placed'], dtype='object')

In [2]:
X = df[["cgpa", "iq", "profile_score"]]

y = df["placed"]

In [8]:
X.head()

   cgpa   iq  profile_score
0  5.97  106             61
1  6.83  113             77
2  6.60  110             61
3  5.54  113             68
4  6.84  102             67

In [9]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: placed, dtype: int64

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [4]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (240, 3)
X_test : (60, 3)
y_train: (240,)
y_test : (60,)

In [5]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

In [6]:
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.85

In [7]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.87      0.85        30
           1       0.86      0.83      0.85        30

    accuracy                           0.85        60
   macro avg       0.85      0.85      0.85        60
weighted avg       0.85      0.85      0.85        60

In [8]:
import pickle

with open("model.pkl", "wb") as file:
    pickle.dump(model, file)

In [9]:
print("Model saved successfully!")

Model saved successfully!

In [10]:
with open("model.pkl", "rb") as file:
    loaded_model = pickle.load(file)

In [11]:
sample = [[8.2, 120, 85]]

prediction = loaded_model.predict(sample)

print(prediction)

[0]

C:\Users\LENOVO-PC\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(